<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_5883c457cf1b5',
        'title' => 'Options',
        'fields' => array (
            array (
                'key' => 'field_5883c64a0b525',
                'label' => 'Suppression éléments sidebar',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_5883c45d4e3f9',
                'label' => 'Affichage',
                'name' => 'affichage',
                'type' => 'checkbox',
                'instructions' => 'Séléctionner les éléments de la sidebar à cacher',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array (
                    'index.php' => 'Tableau de bord',
                    'edit.php' => 'Articles',
                    'edit.php?post_type=page' => 'Pages',
                    'upload.php' => 'Médias',
                    'users.php' => 'Utilisateurs',
                    'tools.php' => 'Options',
                    'themes.php' => 'Apparence',
                    'options-general.php' => 'Réglages',
                    'edit.php?post_type=parrallax' => 'ACF - Parrallax',
                    'edit.php?post_type=portrait' => 'ACF - Portraits',
                    'edit-comments.php' => 'Commentaires',
                    'plugins.php' => 'Extensions',
                    'edit.php?post_type=acf-field-group' => 'ACF',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
            ),
            array (
                'key' => 'field_5883c65a0b526',
                'label' => 'Ajout éléments sidebar',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_5883c6750b527',
                'label' => 'Icone',
                'name' => 'icone',
                'type' => 'repeater',
                'instructions' => '<a target="_blank" href="https://developer.wordpress.org/resource/dashicons/">Liste des icones disponibles sur Wordpress</a>',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5883c6880b528',
                'min' => '',
                'max' => '',
                'layout' => 'block',
                'button_label' => 'Ajouter un élément',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5883c6880b528',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Navigation',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883c69a0b529',
                        'label' => 'Titre sidebar',
                        'name' => 'titre_sidebar',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Navigation',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883c6ab0b52a',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'type' => 'text',
                        'instructions' => 'Lien pour la redirection ( fichier php )',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'nav-menus.php',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883c6d90b52b',
                        'label' => 'Icone',
                        'name' => 'icone',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'dashicons-menu',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883c7010b52c',
                        'label' => 'Position',
                        'name' => 'position',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 2,
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array (
                        'key' => 'field_5883e657b50c0',
                        'label' => 'Sous menu',
                        'name' => 'sous_menu',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                    ),
                    array (
                        'key' => 'field_5883ed4c07fa4',
                        'label' => 'Nom',
                        'name' => 'subpage_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array (
                            array (
                                array (
                                    'field' => 'field_5883e657b50c0',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883ed4507fa3',
                        'label' => 'Id',
                        'name' => 'id',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array (
                            array (
                                array (
                                    'field' => 'field_5883e657b50c0',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-back-office',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;
?>